apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    instance: {{ .Release.Name }}
  {{- if .Values.grafana.labels }}
    {{- toYaml .Values.grafana.labels | nindent 4 }}
  {{- end }}
spec:
  version: {{ .Chart.AppVersion }}
{{- toYaml .Values.grafana.spec | nindent 2 }}
