{{- $tenantName := .Release.Name -}}
{{- $namespaces := .Values.namespaces -}}
{{- range $suffix, $ns := $namespaces.suffixes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-ca-certificates
  name: {{ $tenantName }}-{{ $suffix }}
type: kubernetes.io/tls
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBczCCARqgAwIBAgIUFBQAHNumK9+WHav5+gJLl4jXqc4wCgYIKoZIzj0EAwIw
    GDEWMBQGA1UEAxMNaG9tZWxhYi5sb2NhbDAeFw0yNTExMDMxNjE3NDRaFw0yNjAy
    MDExNjE3NDRaMBgxFjAUBgNVBAMTDWhvbWVsYWIubG9jYWwwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAASzgUgjWgRSGwXZviRlQSj/fhAr8axsDwW4xZV8UJdC1m6r
    evWT78LA4CQA53frm0v8nwFQUHcu0MRABeECdMQ6o0IwQDAOBgNVHQ8BAf8EBAMC
    AqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUE2R4GkTPHRDHRic7/kHuYzvY
    9AswCgYIKoZIzj0EAwIDRwAwRAIgPWJFtWTH8IUPcA8/8KsUx3Jq4IsQ45r/oRBQ
    q6INjFUCICQWSCj0b46eYy2NhN40EePwzEQllKNY3ky2Xb62hk/9
    -----END CERTIFICATE-----
{{- end }}
