{{- if .Values.argocdConnections }}
{{- $top := . -}}
{{- range $instanceName, $instanceSpec := .Values.argocdConnections }}
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{ $top.Values.name }}-{{ $instanceName }}
spec:
  forProvider:
    labels:
  {{- if eq $instanceName "central" }}
    {{- include "cluster.addons" $top | nindent 6 }}
  {{- end }}
    config:
    {{- include "cluster.config" $instanceSpec | nindent 6 }}
    name: {{ $top.Values.name }}
    server: {{ $top.Values.server }}
  providerConfigRef:
    name: argocd-provider
{{- end }}
{{- end }}
