apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  forProvider:
    labels:
      {{- include "cluster.addons" . | nindent 6 }}
      cluster-type: {{ .Values.type }}
    config:
    {{- if (eq .Values.type "management") }}
      tlsClientConfig:
        insecure: true
    {{- end }}
    name: {{ .Values.name }}
    {{- if (eq .Values.type "management") }}
    server: https://kubernetes.default.svc
    {{- end }}
  providerConfigRef:
    name: argocd-provider

