{{- $tenantName := .Values.name -}}
{{- range $env := tuple "dev" "staging" "production" "sandbox" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $tenantName }}-{{ $env }}"
  namespace: tenant-{{ $tenantName }}
spec:
  project: tenants
  destination:
    name: rpi
  sources:
    - repoURL: https://jjsiv-homelab.github.io/infra-helm-charts
      chart: tenant-environment
      targetRevision: 0.1.0
      helm:
        ignoreMissingValueFiles: true
        releaseName: {{ $env }}
        valueFiles:
          - $values/tenants/{{ $tenantName }}/environments/{{ $env }}.yaml
    - repoURL: git@github.com:jjsiv-homelab/tenants-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=background
{{- end }}
