{{- $tenantName := .Values.name -}}
{{- range $envName, $envSpec := .Values.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $tenantName }}-{{ $envName }}"
  namespace: tenant-{{ $tenantName }}
spec:
  project: tenants
  destination:
    name: {{ $envSpec.cluster }}
  sources:
    - repoURL: https://jjsiv-homelab.github.io/infra-helm-charts
      chart: tenant-environment
      targetRevision: 0.*
      helm:
        ignoreMissingValueFiles: true
        releaseName: {{ $tenantName }}
        valueFiles:
          - $values/{{ $tenantName }}/environments/{{ $envName }}.yaml
    - repoURL: git@github.com:jjsiv-homelab/tenants.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=background
{{- end }}
